export interface HayvanKayit{
    id:string;
    vatandasId:number;
    belediyeId:number;
    kafesNo:number;
    cipNo:string;
    kulakNo:string;
    ad:string;
    hayvanTur:number;
    irk:string;
    yas:string;
    cinsiyet:string;
    esgal:string;
    gebeMi:string;
    geldigiTarih:string;
    geldigiAdres:string;
    anamnez:string;
    fotograf:string;
}